image: python:3.9

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  POETRY_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pypoetry"

cache:
  key: ${CI_JOB_NAME}
  paths:
    - .cache/pip
    - .cache/pypoetry

before_script:
  - apt-get update
  - apt-get install -y locales-all
  - python -V
  - pip install poetry
  - poetry config experimental.new-installer false
  - poetry install --no-root --remove-untracked

test:
  script:
    - poetry run pytest --cov=magic --cov-report xml
  artifacts:
    reports:
      cobertura: coverage.xml
